#!/usr/bin/env bash
# =============================================================
# Content IQ — Deployment Script
# Deploys all Azure infrastructure and generates a .env file
#
# Prerequisites:
#   - Azure CLI installed and logged in:  az login
#   - Bicep CLI (bundled with Azure CLI >= 2.20)
#   - jq  (for JSON parsing)
#
# Usage:
#   chmod +x infra/deploy.sh
#   ./infra/deploy.sh
# =============================================================

set -euo pipefail

# ── Config — edit these before running ───────────────────────
SUBSCRIPTION_ID=""          # Target subscription ID
RESOURCE_GROUP="content-iq-rg"
LOCATION="eastus"           # Must match parameters.json
DEPLOYMENT_NAME="contentiq-deploy"

# External API keys (not provisioned via Azure)
TAVILY_API_KEY=""
GROQ_API_KEY=""
ANTHROPIC_API_KEY=""        # optional — only needed for eval/judge

# ─────────────────────────────────────────────────────────────

if [[ -z "$SUBSCRIPTION_ID" ]]; then
  echo "ERROR: Set SUBSCRIPTION_ID at the top of this script before running."
  exit 1
fi

echo "==> Logging in check..."
az account show > /dev/null 2>&1 || { echo "Not logged in. Run: az login"; exit 1; }

echo "==> Setting subscription: $SUBSCRIPTION_ID"
az account set --subscription "$SUBSCRIPTION_ID"

echo "==> Creating resource group: $RESOURCE_GROUP ($LOCATION)"
az group create \
  --name "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --output none

echo "==> Deploying Bicep template..."
DEPLOY_OUTPUT=$(az deployment group create \
  --name "$DEPLOYMENT_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --template-file "$(dirname "$0")/main.bicep" \
  --parameters "$(dirname "$0")/parameters.json" \
  --query "properties.outputs" \
  --output json)

echo "==> Deployment complete. Extracting outputs..."

# Parse outputs
STORAGE_ACCOUNT_NAME=$(echo "$DEPLOY_OUTPUT" | jq -r '.storageAccountName.value')
STORAGE_CONNECTION_STRING=$(echo "$DEPLOY_OUTPUT" | jq -r '.storageConnectionString.value')
OPENAI_ENDPOINT=$(echo "$DEPLOY_OUTPUT" | jq -r '.openAiEndpoint.value')
OPENAI_KEY=$(echo "$DEPLOY_OUTPUT" | jq -r '.openAiKey.value')
CU_ENDPOINT=$(echo "$DEPLOY_OUTPUT" | jq -r '.contentUnderstandingEndpoint.value')
SEARCH_ENDPOINT=$(echo "$DEPLOY_OUTPUT" | jq -r '.searchEndpoint.value')
SEARCH_KEY=$(echo "$DEPLOY_OUTPUT" | jq -r '.searchKey.value')

# Write .env to project root
ENV_FILE="$(dirname "$0")/../.env"

cat > "$ENV_FILE" <<EOF
# Auto-generated by infra/deploy.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT commit this file to git.

# Azure OpenAI (via AI Foundry)
AZURE_OPENAI_ENDPOINT=${OPENAI_ENDPOINT}
AZURE_OPENAI_KEY=${OPENAI_KEY}
AZURE_OPENAI_DEPLOYMENT=gpt-4o
AZURE_OPENAI_EMB_DEPLOYMENT=text-embedding-ada-002
AZURE_OPENAI_API_VERSION=2024-02-15-preview

# Azure AI Search
AZURE_SEARCH_ENDPOINT=${SEARCH_ENDPOINT}
AZURE_SEARCH_KEY=${SEARCH_KEY}
AZURE_SEARCH_INDEX_NAME=content-iq-index

# Azure Content Understanding (same AI Services account as OpenAI)
AZURE_CU_ENDPOINT=${CU_ENDPOINT}
AZURE_CU_KEY=${OPENAI_KEY}

# Azure Blob Storage
AZURE_STORAGE_CONNECTION_STRING=${STORAGE_CONNECTION_STRING}
AZURE_STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
RAW_DOCUMENT_CONTAINER=container
PROCESSED_DOCUMENT_CONTAINER=processed

# External APIs
TAVILY_API_KEY=${TAVILY_API_KEY}
GROQ_API_KEY=${GROQ_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

# Tuning
CONFIDENCE_THRESHOLD=0.6
TOP_K_RESULTS=8
EOF

echo ""
echo "==> .env written to: $ENV_FILE"
echo ""
echo "========================================================"
echo "  NEXT STEPS"
echo "========================================================"
echo ""
echo "  1. Upload your documents to blob storage:"
echo "       az storage blob upload-batch \\"
echo "         --connection-string \"$STORAGE_CONNECTION_STRING\" \\"
echo "         --destination container \\"
echo "         --source ./data/documents"
echo ""
echo "  2. Create the AI Search index:"
echo "       cd backend && python -m ingestion.ingest_all --create-index"
echo ""
echo "  3. Run ingestion (use --skip-cu if you have .cu_cache/):"
echo "       python -m ingestion.ingest_all --skip-cu"
echo ""
echo "  4. Start the backend:"
echo "       uvicorn main:app --reload"
echo ""
echo "  5. Start the frontend:"
echo "       cd frontend && npm run dev"
echo ""
echo "========================================================"
